name: Benchmark Go code

on:
  pull_request:
    branches:
      - main

permissions:
  pull-requests: write

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          show-progress: false

      - name: Set up Go
        uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed # v5.1.0
        with:
          go-version-file: go.ver
          cache: false

      - name: Fetch test rules
        run: make -C cmd/pint/bench fetch

      - name: Benchmark PR branch
        run: |
          make benchmark | tee new.txt

      - name: Benchmark main branch
        run: |
          git fetch origin main
          git reset --hard FETCH_HEAD
          make benchmark | tee old.txt

      - name: Diff benchmarks
        run: |
          git reset --hard ${GITHUB_SHA}
          make benchmark-diff

      - name: Report
        if: ${{ github.event.pull_request.head.repo.full_name == 'cloudflare/pint' }}
        uses: thollander/actions-comment-pull-request@e2c37e53a7d2227b61585343765f73a9ca57eda9 # v3.0.0
        with:
          file-path: benchstat.txt
          comment-tag: benchstat
