name: pint ci

on:
  pull_request:
    branches:
      - main

permissions:
  pull-requests: write

jobs:
  ci:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.head.repo.full_name == 'cloudflare/pint' }}
    steps:
      - name: Check out code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          show-progress: false
          fetch-depth: 0

      - name: Fetch main branch
        run: |
          git fetch origin main
          git checkout main
          git fetch origin $GITHUB_HEAD_REF
          git checkout $GITHUB_HEAD_REF --

      - name: Set up Go
        uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed # v5.1.0
        with:
          go-version-file: go.ver
          cache: false

      - name: Compile pint
        run: make build

      - name: Run pint ci
        run: ./pint -l debug -c .github/pint/pint.hcl ci
        env:
          GITHUB_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
