name: Check go.mod

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions: read-all

jobs:
  go-mod-tidy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
        with:
          show-progress: false

      - name: Set up Go
        uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed # v5.1.0
        with:
          go-version-file: go.ver
          cache: false

      - name: Run go mod tidy
        run: go mod tidy

      - name: Check for local changes
        run: git diff --exit-code
