name: Test Go code

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions: read-all

jobs:
  test-go:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          show-progress: false

      - name: Set up Go
        uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a # v5.2.0
        with:
          go-version-file: go.ver
          cache: false

      - name: Test
        run: make test

      - name: Check for local changes
        run: git diff --exit-code

      # Codecov reporting is unreliable.
      # Re-run report 3 times to have a better
      # chance of success.
      - name: Report code coverage (1)
        uses: codecov/codecov-action@7f8b4b4bde536c465e797be725718b88c5d95e0e # v5.1.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./.cover/coverage.out
          fail_ci_if_error: true
          handle_no_reports_found: true
        continue-on-error: true

      - name: Report code coverage (2)
        uses: codecov/codecov-action@7f8b4b4bde536c465e797be725718b88c5d95e0e # v5.1.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./.cover/coverage.out
          fail_ci_if_error: true
          handle_no_reports_found: true
        continue-on-error: true

      - name: Report code coverage (3)
        uses: codecov/codecov-action@7f8b4b4bde536c465e797be725718b88c5d95e0e # v5.1.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./.cover/coverage.out
          fail_ci_if_error: true
          handle_no_reports_found: true
